from fastapi import FastAPI, Request
from model.risk_engine import predict_risk
from api.github_bot import post_commit_comment

# ✅ create app FIRST
app = FastAPI()


# ---------------- PREDICT API ----------------
@app.post("/predict")
def predict(
    files_changed: int,
    total_changes: int,
    ratio: float,
    large_change: int,
    multi_file: int,
    merge: int
):

    prob, level = predict_risk(
        files_changed,
        total_changes,
        ratio,
        large_change,
        multi_file,
        merge
    )

    return {
        "conflict_probability": float(prob),
        "risk_level": level
    }


# ---------------- GITHUB WEBHOOK ----------------
@app.post("/github-webhook")
async def github_webhook(request: Request):

    payload = await request.json()

    repo_name = payload["repository"]["full_name"]
    commits = payload.get("commits", [])

    files_changed = len(commits)
    total_changes = sum(
        len(c.get("added", [])) +
        len(c.get("removed", []))
        for c in commits
    )

    ratio = 1.0
    large_change = 1 if total_changes > 200 else 0
    multi_file = 1 if files_changed > 3 else 0
    merge = 1

    prob, level = predict_risk(
        files_changed,
        total_changes,
        ratio,
        large_change,
        multi_file,
        merge
    )

    # 🤖 COMMENT MESSAGE
    message = f"""
🤖 **AI Merge Conflict Analysis**

Risk Level: **{level}**
Probability: **{prob:.2f}**

Signals Detected:
- Files Changed: {files_changed}
- Total Changes: {total_changes}
- Large Change: {large_change}
- Multi File Commit: {multi_file}

⚡ Generated by Merge Conflict Predictor AI
"""

    # COMMENT ON EACH COMMIT
    for commit in commits:
        sha = commit["id"]
        post_commit_comment(repo_name, sha, message)

    return {
        "status": "analyzed",
        "risk_level": level,
        "probability": prob
    }
@app.get("/")
def home():
    return {
        "status": "running",
        "service": "AI Merge Conflict Predictor",
        "author": "Praveen Kumar"
    }