from fastapi import FastAPI, Request
from model.risk_engine import predict_risk
from api.github_bot import post_commit_comment
from model.explainer import explain_risk
from model.line_analyzer import detect_risky_lines
from api.github_fetcher import get_commit_changes

# =====================================================
# CREATE FASTAPI APP
# =====================================================
app = FastAPI()


# =====================================================
# PREDICT API (Manual Testing)
# =====================================================
@app.post("/predict")
def predict(
    files_changed: int,
    total_changes: int,
    ratio: float,
    large_change: int,
    multi_file: int,
    merge: int
):
    prob, level = predict_risk(
        files_changed,
        total_changes,
        ratio,
        large_change,
        multi_file,
        merge
    )

    reasons = explain_risk({
        "files_changed": files_changed,
        "total_changes": total_changes,
        "multi_file_change": multi_file,
        "merge_activity": merge
    })

    return {
        "conflict_probability": float(prob),
        "risk_level": level,
        "reasons": reasons
    }


# =====================================================
# GITHUB WEBHOOK
# =====================================================
@app.post("/github-webhook")
async def github_webhook(request: Request):

    payload = await request.json()

    repo_name = payload.get("repository", {}).get("full_name")
    commits = payload.get("commits", [])

    if not repo_name or not commits:
        return {"status": "no data"}

    # -------------------------------------------------
    # FEATURE EXTRACTION
    # -------------------------------------------------
    files_changed = 0
    total_changes = 0

    for commit in commits:
        sha = commit["id"]
        f, c = get_commit_changes(repo_name, sha)
        files_changed += f
        total_changes += c

    # Proper ratio calculation
    ratio = total_changes / max(files_changed, 1)

    large_change = 1 if total_changes > 200 else 0
    multi_file = 1 if files_changed > 3 else 0
    merge = 1

    # -------------------------------------------------
    # RISK PREDICTION
    # -------------------------------------------------
    prob, level = predict_risk(
        files_changed,
        total_changes,
        ratio,
        large_change,
        multi_file,
        merge
    )

    # -------------------------------------------------
    # EXPLAINABILITY
    # -------------------------------------------------
    reasons = explain_risk({
        "files_changed": files_changed,
        "total_changes": total_changes,
        "multi_file_change": multi_file,
        "merge_activity": merge
    })

    reason_text = (
        "\n".join([f"- {r}" for r in reasons])
        if reasons else "- No strong risk signals detected"
    )

    # -------------------------------------------------
    # RISKY AREA DETECTION
    # -------------------------------------------------
    try:
        risky_areas = detect_risky_lines(commits)
    except Exception as e:
        print("Risk detection error:", e)
        risky_areas = []

    risk_area_text = ""
    for r in risky_areas:
        risk_area_text += f"\n- {r.get('file')} → {r.get('reason')}"

    if not risk_area_text:
        risk_area_text = "\n- No risky files detected"

    # -------------------------------------------------
    # AUTO RESOLVER POLICY ENGINE
    # -------------------------------------------------
    auto_fix_message = ""

    HIGH_RATIO_THRESHOLD = 120
    HIGH_CHANGE_THRESHOLD = 400

    trigger_auto = (
        level == "HIGH"
        or ratio > HIGH_RATIO_THRESHOLD
        or total_changes > HIGH_CHANGE_THRESHOLD
    )

    if trigger_auto:
        auto_fix_message = f"""
---
### ⚡ Auto Resolver Triggered
Preventive conflict mitigation executed.

- Risk Level: {level}
- Change Ratio: {ratio:.2f}
- Total Changes: {total_changes}
"""

    # -------------------------------------------------
    # COMMENT MESSAGE
    # -------------------------------------------------
    message = f"""
🤖 **AI Merge Conflict Analysis**

### 🔥 Risk Level: **{level}**
### 📊 Probability: **{prob:.2f}**

---

### ⚠️ Why risk is {level}:
{reason_text}

---

### 📂 Risky Areas
{risk_area_text}

---

### 📈 Signals
- Files Changed: {files_changed}
- Total Changes: {total_changes}
- Change Ratio: {ratio:.2f}
- Large Change: {large_change}
- Multi File Commit: {multi_file}

{auto_fix_message}

⚡ Generated by **Merge Conflict Predictor AI**
"""

    # -------------------------------------------------
    # POST COMMENT ON EACH COMMIT
    # -------------------------------------------------
    for commit in commits:
        sha = commit["id"]
        post_commit_comment(repo_name, sha, message)

    return {
        "status": "analyzed",
        "risk_level": level,
        "probability": float(prob),
        "ratio": ratio,
        "auto_resolver_triggered": trigger_auto
    }


# =====================================================
# HEALTH CHECK
# =====================================================
@app.get("/")
def home():
    return {
        "status": "running",
        "service": "AI Merge Conflict Predictor"
    }